[package]
name = "piston-example-freetype"
version = "0.0.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = []

[[bin]]
name = "piston-example-freetype"
path = "src/main.rs"

[dependencies]
piston = "0.42.0"
piston2d-opengl_graphics = "0.61.0"
piston2d-graphics = "0.31.0"
pistoncore-sdl2_window = "0.55.0"
freetype-rs = "0.19.0"
find_folder = "0.3.0"
